# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [2]:
!pip install tensorflow

Collecting tensorflow
  Downloading tensorflow-2.11.0-cp39-cp39-win_amd64.whl (1.9 kB)
Collecting tensorflow-intel==2.11.0
  Downloading tensorflow_intel-2.11.0-cp39-cp39-win_amd64.whl (266.3 MB)
     -------------------------------------- 266.3/266.3 MB 4.5 MB/s eta 0:00:00
Collecting grpcio<2.0,>=1.24.3
  Downloading grpcio-1.51.3-cp39-cp39-win_amd64.whl (3.7 MB)
     ---------------------------------------- 3.7/3.7 MB 6.1 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\ritvi\anaconda3\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow) (4.3.0)
Collecting gast<=0.4.0,>=0.2.1
  Downloading gast-0.4.0-py3-none-any.whl (9.8 kB)
Requirement already satisfied: h5py>=2.9.0 in c:\users\ritvi\anaconda3\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow) (3.7.0)
Collecting astunparse>=1.6.0
  Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: numpy>=1.20 in c:\users\ritvi\anaconda3\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow) (1.21.5)
Collecting flatbuffers>=2.0
  Downloading flatbuffers-23.1.21-py2.py3-none-any.whl (26 kB)
Collecting keras<2.12,>=2.11.0
  Downloading keras-2.11.0-py2.py3-none-any.whl (1.7 MB)
     ---------------------------------------- 1.7/1.7 MB 6.3 MB/s eta 0:00:00
Collecting google-pasta>=0.1.1
  Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
     ---------------------------------------- 57.5/57.5 kB ? eta 0:00:00
Collecting opt-einsum>=2.3.2
  Downloading opt_einsum-3.3.0-py3-none-any.whl (65 kB)
     ---------------------------------------- 65.5/65.5 kB ? eta 0:00:00
Collecting absl-py>=1.0.0
  Downloading absl_py-1.4.0-py3-none-any.whl (126 kB)
     -------------------------------------- 126.5/126.5 kB 3.6 MB/s eta 0:00:00
Collecting tensorflow-estimator<2.12,>=2.11.0
  Downloading tensorflow_estimator-2.11.0-py2.py3-none-any.whl (439 kB)
     -------------------------------------- 439.2/439.2 kB 5.5 MB/s eta 0:00:00
Collecting protobuf<3.20,>=3.9.2
  Downloading protobuf-3.19.6-cp39-cp39-win_amd64.whl (895 kB)
     -------------------------------------- 895.9/895.9 kB 6.3 MB/s eta 0:00:00
Requirement already satisfied: wrapt>=1.11.0 in c:\users\ritvi\anaconda3\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow) (1.14.1)
Requirement already satisfied: packaging in c:\users\ritvi\anaconda3\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow) (21.3)
Collecting tensorflow-io-gcs-filesystem>=0.23.1
  Downloading tensorflow_io_gcs_filesystem-0.31.0-cp39-cp39-win_amd64.whl (1.5 MB)
     ---------------------------------------- 1.5/1.5 MB 6.3 MB/s eta 0:00:00
Collecting libclang>=13.0.0
  Downloading libclang-15.0.6.1-py2.py3-none-win_amd64.whl (23.2 MB)
     ---------------------------------------- 23.2/23.2 MB 6.0 MB/s eta 0:00:00
Requirement already satisfied: six>=1.12.0 in c:\users\ritvi\anaconda3\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow) (1.16.0)
Collecting termcolor>=1.1.0
  Downloading termcolor-2.2.0-py3-none-any.whl (6.6 kB)
Collecting tensorboard<2.12,>=2.11
  Downloading tensorboard-2.11.2-py3-none-any.whl (6.0 MB)
     ---------------------------------------- 6.0/6.0 MB 5.7 MB/s eta 0:00:00
Requirement already satisfied: setuptools in c:\users\ritvi\anaconda3\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow) (65.5.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\ritvi\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.11.0->tensorflow) (0.37.1)
Collecting tensorboard-plugin-wit>=1.6.0
  Downloading tensorboard_plugin_wit-1.8.1-py3-none-any.whl (781 kB)
     -------------------------------------- 781.3/781.3 kB 3.1 MB/s eta 0:00:00
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\ritvi\anaconda3\lib\site-packages (from tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow) (2.0.3)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\ritvi\anaconda3\lib\site-packages (from tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow) (2.28.1)
Requirement already satisfied: markdown>=2.6.8 in c:\users\ritvi\anaconda3\lib\site-packages (from tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow) (3.3.4)
Collecting tensorboard-data-server<0.7.0,>=0.6.0
  Downloading tensorboard_data_server-0.6.1-py3-none-any.whl (2.4 kB)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Downloading google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
Collecting google-auth<3,>=1.6.3
  Downloading google_auth-2.16.2-py2.py3-none-any.whl (177 kB)
     -------------------------------------- 177.2/177.2 kB 2.7 MB/s eta 0:00:00
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\ritvi\anaconda3\lib\site-packages (from packaging->tensorflow-intel==2.11.0->tensorflow) (3.0.9)
Collecting rsa<5,>=3.1.4
  Downloading rsa-4.9-py3-none-any.whl (34 kB)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\ritvi\anaconda3\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow) (0.2.8)
Collecting cachetools<6.0,>=2.0.0
  Downloading cachetools-5.3.0-py3-none-any.whl (9.3 kB)
Collecting requests-oauthlib>=0.7.0
  Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ritvi\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow) (2022.9.24)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\ritvi\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ritvi\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\ritvi\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow) (1.26.12)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\ritvi\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow) (0.4.8)
Collecting oauthlib>=3.0.0
  Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
     -------------------------------------- 151.7/151.7 kB 2.3 MB/s eta 0:00:00
Installing collected packages: tensorboard-plugin-wit, libclang, flatbuffers, termcolor, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, rsa, protobuf, opt-einsum, oauthlib, keras, grpcio, google-pasta, gast, cachetools, astunparse, absl-py, requests-oauthlib, google-auth, google-auth-oauthlib, tensorboard, tensorflow-intel, tensorflow
Successfully installed absl-py-1.4.0 astunparse-1.6.3 cachetools-5.3.0 flatbuffers-23.1.21 gast-0.4.0 google-auth-2.16.2 google-auth-oauthlib-0.4.6 google-pasta-0.2.0 grpcio-1.51.3 keras-2.11.0 libclang-15.0.6.1 oauthlib-3.2.2 opt-einsum-3.3.0 protobuf-3.19.6 requests-oauthlib-1.3.1 rsa-4.9 tensorboard-2.11.2 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.1 tensorflow-2.11.0 tensorflow-estimator-2.11.0 tensorflow-intel-2.11.0 tensorflow-io-gcs-filesystem-0.31.0 termcolor-2.2.0

In [57]:
# Imports
import pandas as pd
import numpy as np
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.decomposition import PCA
from datetime import date

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [12]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv(Path("C:/Users/ritvi/Downloads/Starter_Code (3)/Starter_Code/Resources/applicants_data.csv"))

# Review the DataFrame
applicant_data_df.head()
applicant_data_df.head(-5)

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...,...
34289,990382020,SOLEA WATER,T3,Independent,C1000,Preservation,Trust,1,25000-99999,N,20197,1
34290,996006031,DISABLED AMERICAN VETERANS,T4,CompanySponsored,C3000,Preservation,Association,1,1-9999,N,5000,0
34291,996008763,AMERICAN ASSOCIATION OF UNIVERSITY WOMEN,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34292,996008993,DISABLED AMERICAN VETERANS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34293,996009208,CHI EPSILON 49,T3,CompanySponsored,C1000,Preservation,Association,1,0,N,5000,1

In [13]:
# Review the data types associated with the columns
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [14]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(columns=['EIN','NAME'])

# Review the DataFrame
applicant_data_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [16]:
# Create a list of categorical variables 
categorical_variables = list(applicant_data_df.dtypes[applicant_data_df.dtypes=='object'].index)

# Display the categorical variables list
categorical_variables

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [17]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [18]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

In [20]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(encoded_data, columns=enc.get_feature_names(categorical_variables))

# Review the DataFrame
encoded_df.head()

C:\Users\ritvi\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [21]:
non_categorical_variables = list(applicant_data_df.dtypes[applicant_data_df.dtypes!='object'].index)
non_categorical_variables

['STATUS', 'ASK_AMT', 'IS_SUCCESSFUL']

In [22]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
encoded_df = pd.concat([applicant_data_df[non_categorical_variables], encoded_df], axis=1)
# Review the Dataframe
encoded_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [23]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df['IS_SUCCESSFUL']

# Display a sample of y
y.head()

0    1
1    1
2    0
3    1
4    1
Name: IS_SUCCESSFUL, dtype: int64

In [24]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.drop(columns=['IS_SUCCESSFUL'])

# Review the features DataFrame
X.head()

,STATUS,ASK_AMT,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 6: Split the features and target sets into training and testing datasets.

In [25]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X,y)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [26]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [27]:
# Define the the number of inputs (features) to the model
number_input_features = X.shape[1]

# Review the number of features
number_input_features

116

In [31]:
# Define the number of neurons in the output layer
number_output_neurons = 2

In [32]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  np.ceil(np.sqrt(number_input_features * number_output_neurons))

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

16.0

In [33]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  np.ceil(np.sqrt(hidden_nodes_layer1 * number_output_neurons))

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

6.0

In [34]:
# Create the Sequential model instance
nn = Sequential()

In [35]:
# Add the first hidden layer
nn.add(
    Dense(
        units=hidden_nodes_layer1,
        activation='relu',
        input_dim=number_input_features
    )
)

In [36]:
# Add the second hidden layer
nn.add(
    Dense(
        units=hidden_nodes_layer2,
        activation='relu'
    )
)

In [37]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(
    Dense(
        units=1,
        activation='sigmoid'
    )
)

In [38]:
# Display the Sequential model summary
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 16)                1872

 dense_1 (Dense)             (None, 6)                 102

 dense_2 (Dense)             (None, 1)                 7

=================================================================
Total params: 1,981
Trainable params: 1,981
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [39]:
# Compile the Sequential model
nn.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [40]:
# Fit the model using 50 epochs and the training data
nn_model=nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 1s 795us/step - loss: 0.5923 - accuracy: 0.7110
Epoch 2/50
804/804 [==============================] - 1s 776us/step - loss: 0.5590 - accuracy: 0.7271
Epoch 3/50
804/804 [==============================] - 1s 764us/step - loss: 0.5539 - accuracy: 0.7289
Epoch 4/50
804/804 [==============================] - 1s 776us/step - loss: 0.5522 - accuracy: 0.7288
Epoch 5/50
804/804 [==============================] - 1s 734us/step - loss: 0.5503 - accuracy: 0.7307
Epoch 6/50
804/804 [==============================] - 1s 822us/step - loss: 0.5498 - accuracy: 0.7324
Epoch 7/50
804/804 [==============================] - 1s 756us/step - loss: 0.5486 - accuracy: 0.7320
Epoch 8/50
804/804 [==============================] - 1s 747us/step - loss: 0.5484 - accuracy: 0.7308
Epoch 9/50
804/804 [==============================] - 1s 756us/step - loss: 0.5475 - accuracy: 0.7324
Epoch 10/50
804/804 [==============================] - 1s 755us/step - loss: 0.5470 - accuracy: 0.7327
Epoch 11/50
804/804 [==============================] - 1s 757us/step - loss: 0.5471 - accuracy: 0.7322
Epoch 12/50
804/804 [==============================] - 1s 752us/step - loss: 0.5466 - accuracy: 0.7328
Epoch 13/50
804/804 [==============================] - 1s 754us/step - loss: 0.5458 - accuracy: 0.7329
Epoch 14/50
804/804 [==============================] - 1s 735us/step - loss: 0.5457 - accuracy: 0.7329
Epoch 15/50
804/804 [==============================] - 1s 739us/step - loss: 0.5455 - accuracy: 0.7329
Epoch 16/50
804/804 [==============================] - 1s 746us/step - loss: 0.5450 - accuracy: 0.7329
Epoch 17/50
804/804 [==============================] - 1s 746us/step - loss: 0.5448 - accuracy: 0.7331
Epoch 18/50
804/804 [==============================] - 1s 749us/step - loss: 0.5446 - accuracy: 0.7336
Epoch 19/50
804/804 [==============================] - 1s 746us/step - loss: 0.5444 - accuracy: 0.7348
Epoch 20/50
804/804 [==============================] - 1s 756us/step - loss: 0.5440 - accuracy: 0.7334
Epoch 21/50
804/804 [==============================] - 1s 740us/step - loss: 0.5437 - accuracy: 0.7342
Epoch 22/50
804/804 [==============================] - 1s 770us/step - loss: 0.5433 - accuracy: 0.7359
Epoch 23/50
804/804 [==============================] - 1s 751us/step - loss: 0.5434 - accuracy: 0.7338
Epoch 24/50
804/804 [==============================] - 1s 757us/step - loss: 0.5434 - accuracy: 0.7348
Epoch 25/50
804/804 [==============================] - 1s 742us/step - loss: 0.5429 - accuracy: 0.7345
Epoch 26/50
804/804 [==============================] - 1s 747us/step - loss: 0.5425 - accuracy: 0.7352
Epoch 27/50
804/804 [==============================] - 1s 785us/step - loss: 0.5424 - accuracy: 0.7344
Epoch 28/50
804/804 [==============================] - 1s 766us/step - loss: 0.5425 - accuracy: 0.7338
Epoch 29/50
804/804 [==============================] - 1s 755us/step - loss: 0.5421 - accuracy: 0.7360
Epoch 30/50
804/804 [==============================] - 1s 755us/step - loss: 0.5420 - accuracy: 0.7359
Epoch 31/50
804/804 [==============================] - 1s 752us/step - loss: 0.5416 - accuracy: 0.7359
Epoch 32/50
804/804 [==============================] - 1s 769us/step - loss: 0.5413 - accuracy: 0.7361
Epoch 33/50
804/804 [==============================] - 1s 755us/step - loss: 0.5414 - accuracy: 0.7356
Epoch 34/50
804/804 [==============================] - 1s 757us/step - loss: 0.5410 - accuracy: 0.7349
Epoch 35/50
804/804 [==============================] - 1s 753us/step - loss: 0.5411 - accuracy: 0.7362
Epoch 36/50
804/804 [==============================] - 1s 750us/step - loss: 0.5413 - accuracy: 0.7353
Epoch 37/50
804/804 [==============================] - 1s 772us/step - loss: 0.5408 - accuracy: 0.7369
Epoch 38/50
804/804 [==============================] - 1s 756us/step - loss: 0.5410 - accuracy: 0.7369
Epoch 39/50
804/804 [==============================] - 1s 756us/step - loss: 0.5402 - accuracy: 0.7360
Epoch 40/50
804/804 [==============================] - 1s 759us/step - loss: 0.5408 - accuracy: 0.7361
Epoch 41/50
804/804 [==============================] - 1s 755us/step - loss: 0.5404 - accuracy: 0.7355
Epoch 42/50
804/804 [==============================] - 1s 750us/step - loss: 0.5401 - accuracy: 0.7379
Epoch 43/50
804/804 [==============================] - 1s 744us/step - loss: 0.5403 - accuracy: 0.7369
Epoch 44/50
804/804 [==============================] - 1s 739us/step - loss: 0.5405 - accuracy: 0.7370
Epoch 45/50
804/804 [==============================] - 1s 739us/step - loss: 0.5399 - accuracy: 0.7362
Epoch 46/50
804/804 [==============================] - 1s 760us/step - loss: 0.5402 - accuracy: 0.7364
Epoch 47/50
804/804 [==============================] - 1s 756us/step - loss: 0.5398 - accuracy: 0.7365
Epoch 48/50
804/804 [==============================] - 1s 747us/step - loss: 0.5397 - accuracy: 0.7363
Epoch 49/50
804/804 [==============================] - 1s 759us/step - loss: 0.5395 - accuracy: 0.7376
Epoch 50/50
804/804 [==============================] - 1s 735us/step - loss: 0.5396 - accuracy: 0.7364

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [41]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5475 - accuracy: 0.7310 - 280ms/epoch - 1ms/step
Loss: 0.5474579930305481, Accuracy: 0.7309620976448059

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [43]:
# Set the model's file path
file_path = Path('C:/Users/ritvi/Downloads/Starter_Code (3)/Starter_Code/Resources/AlphabetSoup.h5')

# Export your model to a HDF5 file
nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [44]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [47]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [48]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = (number_input_features + 1) // 2

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

58

In [49]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [50]:
# First hidden layer
nn_A1.add(Dense(units=hidden_nodes_layer1_A1, input_dim=number_input_features, activation="relu"))


# Output layer
nn_A1.add(Dense(units=1, activation="sigmoid"))


# Check the structure of the model
nn_A1.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 58)                6786

 dense_4 (Dense)             (None, 1)                 59

=================================================================
Total params: 6,845
Trainable params: 6,845
Non-trainable params: 0
_________________________________________________________________

In [54]:
# Compile the Sequential model
nn_A1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [56]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 1s 722us/step - loss: 0.5924 - accuracy: 0.7177
Epoch 2/50
804/804 [==============================] - 1s 751us/step - loss: 0.5604 - accuracy: 0.7294
Epoch 3/50
804/804 [==============================] - 1s 754us/step - loss: 0.5544 - accuracy: 0.7300
Epoch 4/50
804/804 [==============================] - 1s 732us/step - loss: 0.5536 - accuracy: 0.7308
Epoch 5/50
804/804 [==============================] - 1s 717us/step - loss: 0.5529 - accuracy: 0.7317
Epoch 6/50
804/804 [==============================] - 1s 737us/step - loss: 0.5515 - accuracy: 0.7314
Epoch 7/50
804/804 [==============================] - 1s 727us/step - loss: 0.5494 - accuracy: 0.7324
Epoch 8/50
804/804 [==============================] - 1s 767us/step - loss: 0.5496 - accuracy: 0.7332
Epoch 9/50
804/804 [==============================] - 1s 766us/step - loss: 0.5490 - accuracy: 0.7315
Epoch 10/50
804/804 [==============================] - 1s 777us/step - loss: 0.5484 - accuracy: 0.7327
Epoch 11/50
804/804 [==============================] - 1s 781us/step - loss: 0.5483 - accuracy: 0.7317
Epoch 12/50
804/804 [==============================] - 1s 779us/step - loss: 0.5478 - accuracy: 0.7328
Epoch 13/50
804/804 [==============================] - 1s 755us/step - loss: 0.5463 - accuracy: 0.7341
Epoch 14/50
804/804 [==============================] - 1s 740us/step - loss: 0.5470 - accuracy: 0.7334
Epoch 15/50
804/804 [==============================] - 1s 791us/step - loss: 0.5466 - accuracy: 0.7332
Epoch 16/50
804/804 [==============================] - 1s 790us/step - loss: 0.5461 - accuracy: 0.7335
Epoch 17/50
804/804 [==============================] - 1s 741us/step - loss: 0.5461 - accuracy: 0.7343
Epoch 18/50
804/804 [==============================] - 1s 771us/step - loss: 0.5449 - accuracy: 0.7341
Epoch 19/50
804/804 [==============================] - 1s 740us/step - loss: 0.5450 - accuracy: 0.7335
Epoch 20/50
804/804 [==============================] - 1s 739us/step - loss: 0.5449 - accuracy: 0.7353
Epoch 21/50
804/804 [==============================] - 1s 774us/step - loss: 0.5451 - accuracy: 0.7341
Epoch 22/50
804/804 [==============================] - 1s 731us/step - loss: 0.5445 - accuracy: 0.7339
Epoch 23/50
804/804 [==============================] - 1s 766us/step - loss: 0.5442 - accuracy: 0.7339
Epoch 24/50
804/804 [==============================] - 1s 760us/step - loss: 0.5441 - accuracy: 0.7353
Epoch 25/50
804/804 [==============================] - 1s 757us/step - loss: 0.5435 - accuracy: 0.7352
Epoch 26/50
804/804 [==============================] - 1s 771us/step - loss: 0.5437 - accuracy: 0.7353
Epoch 27/50
804/804 [==============================] - 1s 777us/step - loss: 0.5433 - accuracy: 0.7355
Epoch 28/50
804/804 [==============================] - 1s 754us/step - loss: 0.5436 - accuracy: 0.7360
Epoch 29/50
804/804 [==============================] - 1s 735us/step - loss: 0.5426 - accuracy: 0.7356
Epoch 30/50
804/804 [==============================] - 1s 757us/step - loss: 0.5431 - accuracy: 0.7355
Epoch 31/50
804/804 [==============================] - 1s 757us/step - loss: 0.5426 - accuracy: 0.7359
Epoch 32/50
804/804 [==============================] - 1s 805us/step - loss: 0.5426 - accuracy: 0.7355
Epoch 33/50
804/804 [==============================] - 1s 745us/step - loss: 0.5417 - accuracy: 0.7345
Epoch 34/50
804/804 [==============================] - 1s 756us/step - loss: 0.5425 - accuracy: 0.7352
Epoch 35/50
804/804 [==============================] - 1s 737us/step - loss: 0.5419 - accuracy: 0.7357
Epoch 36/50
804/804 [==============================] - 1s 770us/step - loss: 0.5420 - accuracy: 0.7355
Epoch 37/50
804/804 [==============================] - 1s 815us/step - loss: 0.5418 - accuracy: 0.7357
Epoch 38/50
804/804 [==============================] - 1s 740us/step - loss: 0.5414 - accuracy: 0.7367
Epoch 39/50
804/804 [==============================] - 1s 760us/step - loss: 0.5417 - accuracy: 0.7358
Epoch 40/50
804/804 [==============================] - 1s 752us/step - loss: 0.5413 - accuracy: 0.7356
Epoch 41/50
804/804 [==============================] - 1s 754us/step - loss: 0.5415 - accuracy: 0.7359
Epoch 42/50
804/804 [==============================] - 1s 805us/step - loss: 0.5419 - accuracy: 0.7360
Epoch 43/50
804/804 [==============================] - 1s 755us/step - loss: 0.5410 - accuracy: 0.7359
Epoch 44/50
804/804 [==============================] - 1s 746us/step - loss: 0.5409 - accuracy: 0.7357
Epoch 45/50
804/804 [==============================] - 1s 746us/step - loss: 0.5410 - accuracy: 0.7355
Epoch 46/50
804/804 [==============================] - 1s 762us/step - loss: 0.5410 - accuracy: 0.7371
Epoch 47/50
804/804 [==============================] - 1s 806us/step - loss: 0.5409 - accuracy: 0.7361
Epoch 48/50
804/804 [==============================] - 1s 781us/step - loss: 0.5406 - accuracy: 0.7357
Epoch 49/50
804/804 [==============================] - 1s 761us/step - loss: 0.5407 - accuracy: 0.7370
Epoch 50/50
804/804 [==============================] - 1s 761us/step - loss: 0.5407 - accuracy: 0.7360

#### Alternative Model 2

In [74]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [75]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [76]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = (number_input_features * 2)

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

232

In [77]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [78]:
# First hidden layer
nn_A2.add(Dense(input_dim=number_input_features, units=hidden_nodes_layer1_A2, activation="relu"))

# Output layer
nn_A2.add(Dense(units=number_output_neurons_A2, activation="sigmoid"))

# Check the structure of the model
nn_A2.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_12 (Dense)            (None, 232)               27144

 dense_13 (Dense)            (None, 1)                 233

=================================================================
Total params: 27,377
Trainable params: 27,377
Non-trainable params: 0
_________________________________________________________________

In [79]:
# Compile the model
nn_A2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [80]:
# Fit the model
nn_A2.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 1s 821us/step - loss: 0.5836 - accuracy: 0.7167
Epoch 2/50
804/804 [==============================] - 1s 843us/step - loss: 0.5628 - accuracy: 0.7281
Epoch 3/50
804/804 [==============================] - 1s 847us/step - loss: 0.5576 - accuracy: 0.7305
Epoch 4/50
804/804 [==============================] - 1s 840us/step - loss: 0.5555 - accuracy: 0.7300
Epoch 5/50
804/804 [==============================] - 1s 850us/step - loss: 0.5540 - accuracy: 0.7294
Epoch 6/50
804/804 [==============================] - 1s 851us/step - loss: 0.5525 - accuracy: 0.7312
Epoch 7/50
804/804 [==============================] - 1s 843us/step - loss: 0.5523 - accuracy: 0.7313
Epoch 8/50
804/804 [==============================] - 1s 835us/step - loss: 0.5504 - accuracy: 0.7311
Epoch 9/50
804/804 [==============================] - 1s 867us/step - loss: 0.5508 - accuracy: 0.7312
Epoch 10/50
804/804 [==============================] - 1s 843us/step - loss: 0.5501 - accuracy: 0.7324
Epoch 11/50
804/804 [==============================] - 1s 852us/step - loss: 0.5502 - accuracy: 0.7326
Epoch 12/50
804/804 [==============================] - 1s 850us/step - loss: 0.5495 - accuracy: 0.7321
Epoch 13/50
804/804 [==============================] - 1s 833us/step - loss: 0.5481 - accuracy: 0.7329
Epoch 14/50
804/804 [==============================] - 1s 858us/step - loss: 0.5473 - accuracy: 0.7341
Epoch 15/50
804/804 [==============================] - 1s 879us/step - loss: 0.5477 - accuracy: 0.7342
Epoch 16/50
804/804 [==============================] - 1s 841us/step - loss: 0.5470 - accuracy: 0.7332
Epoch 17/50
804/804 [==============================] - 1s 808us/step - loss: 0.5478 - accuracy: 0.7332
Epoch 18/50
804/804 [==============================] - 1s 802us/step - loss: 0.5473 - accuracy: 0.7334
Epoch 19/50
804/804 [==============================] - 1s 851us/step - loss: 0.5457 - accuracy: 0.7355
Epoch 20/50
804/804 [==============================] - 1s 818us/step - loss: 0.5457 - accuracy: 0.7332
Epoch 21/50
804/804 [==============================] - 1s 801us/step - loss: 0.5446 - accuracy: 0.7352
Epoch 22/50
804/804 [==============================] - 1s 805us/step - loss: 0.5453 - accuracy: 0.7331
Epoch 23/50
804/804 [==============================] - 1s 822us/step - loss: 0.5450 - accuracy: 0.7352
Epoch 24/50
804/804 [==============================] - 1s 810us/step - loss: 0.5449 - accuracy: 0.7339
Epoch 25/50
804/804 [==============================] - 1s 808us/step - loss: 0.5438 - accuracy: 0.7347
Epoch 26/50
804/804 [==============================] - 1s 823us/step - loss: 0.5448 - accuracy: 0.7353
Epoch 27/50
804/804 [==============================] - 1s 802us/step - loss: 0.5489 - accuracy: 0.7353
Epoch 28/50
804/804 [==============================] - 1s 818us/step - loss: 0.5442 - accuracy: 0.7346
Epoch 29/50
804/804 [==============================] - 1s 832us/step - loss: 0.5435 - accuracy: 0.7340
Epoch 30/50
804/804 [==============================] - 1s 806us/step - loss: 0.5425 - accuracy: 0.7357
Epoch 31/50
804/804 [==============================] - 1s 810us/step - loss: 0.5425 - accuracy: 0.7345
Epoch 32/50
804/804 [==============================] - 1s 798us/step - loss: 0.5425 - accuracy: 0.7347
Epoch 33/50
804/804 [==============================] - 1s 828us/step - loss: 0.5427 - accuracy: 0.7361
Epoch 34/50
804/804 [==============================] - 1s 815us/step - loss: 0.5426 - accuracy: 0.7337
Epoch 35/50
804/804 [==============================] - 1s 806us/step - loss: 0.5469 - accuracy: 0.7368
Epoch 36/50
804/804 [==============================] - 1s 806us/step - loss: 0.5414 - accuracy: 0.7355
Epoch 37/50
804/804 [==============================] - 1s 815us/step - loss: 0.5416 - accuracy: 0.7364
Epoch 38/50
804/804 [==============================] - 1s 830us/step - loss: 0.5423 - accuracy: 0.7353
Epoch 39/50
804/804 [==============================] - 1s 827us/step - loss: 0.5426 - accuracy: 0.7350
Epoch 40/50
804/804 [==============================] - 1s 833us/step - loss: 0.5410 - accuracy: 0.7365
Epoch 41/50
804/804 [==============================] - 1s 821us/step - loss: 0.5404 - accuracy: 0.7361
Epoch 42/50
804/804 [==============================] - 1s 825us/step - loss: 0.5461 - accuracy: 0.7353
Epoch 43/50
804/804 [==============================] - 1s 856us/step - loss: 0.5404 - accuracy: 0.7365
Epoch 44/50
804/804 [==============================] - 1s 836us/step - loss: 0.5406 - accuracy: 0.7364
Epoch 45/50
804/804 [==============================] - 1s 863us/step - loss: 0.5408 - accuracy: 0.7358
Epoch 46/50
804/804 [==============================] - 1s 825us/step - loss: 0.5406 - accuracy: 0.7364
Epoch 47/50
804/804 [==============================] - 1s 847us/step - loss: 0.5415 - accuracy: 0.7364
Epoch 48/50
804/804 [==============================] - 1s 822us/step - loss: 0.5499 - accuracy: 0.7359
Epoch 49/50
804/804 [==============================] - 1s 820us/step - loss: 0.5394 - accuracy: 0.7382
Epoch 50/50
804/804 [==============================] - 1s 827us/step - loss: 0.5407 - accuracy: 0.7356

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [81]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 0s - loss: 0.5475 - accuracy: 0.7310 - 166ms/epoch - 620us/step
Loss: 0.5474579930305481, Accuracy: 0.7309620976448059

In [83]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 0s - loss: 0.5498 - accuracy: 0.7304 - 166ms/epoch - 620us/step
Loss: 0.5498107671737671, Accuracy: 0.7303789854049683

In [84]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 0s - loss: 0.5600 - accuracy: 0.7315 - 246ms/epoch - 916us/step
Loss: 0.5600187182426453, Accuracy: 0.7315452098846436

### Step 3: Save each of your alternative models as an HDF5 file.

In [87]:
# Set the file path for the first alternative model
file_path_A1 = Path('C:/Users/ritvi/Downloads/Starter_Code (3)/Starter_Code/Resources/AlphabetSoupA1.h5')

# Export your model to a HDF5 file
nn_A1.save(file_path_A1)

In [88]:
# Set the file path for the second alternative model
file_path_A2 = Path('C:/Users/ritvi/Downloads/Starter_Code (3)/Starter_Code/Resources/AlphabetSoupA2.h5')


# Export your model to a HDF5 file
nn_A2.save(file_path_A2)